name: Check Build Environment

on:
  workflow_dispatch:

env:
    GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON}}
 
jobs:
  validate:
    name: Check Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            install: true

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Validate Build Environment
        run: |
            gcloud --version
            terraform --version
            docker --version
            packer --version
            echo $GCP_CREDENTIALS_JSON > credentials.json
            echo "NOTE: Validating credentials.json and test the gcloud command"

            # Check if the file "./credentials.json" exists
            if [[ ! -f "./credentials.json" ]]; then
                echo "ERROR: The file './credentials.json' does not exist." >&2
                exit 1
            fi

            gcloud auth activate-service-account --key-file="./credentials.json"

