name: Check Build Environment

on:
  workflow_dispatch:

env:
    GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON}}
 
jobs:
  validate:
    name: Check Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
            install: true

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2

      - name: Validate Build Environment
        run: |
            gcloud --version
            terraform --version
            docker --version
            packer --version
