name: Destroy Solution

on:
  workflow_dispatch:

env:
  GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

jobs:
  phase_0:
    runs-on: ubuntu-latest
    name: Destroy Cloud Run

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destroy Cloud Run Instances
        run: |
            echo $GCP_CREDENTIALS_JSON > credentials.json
            export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/credentials.json"
            cd "03-cloudrun"
            terraform init
            terraform destroy -auto-approve
            cd ..

  phase_1:
    runs-on: ubuntu-latest
    needs: phase_0
    name: Destroy GAR Instance

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destroy GAR
        run: |
            echo $GCP_CREDENTIALS_JSON > credentials.json
            export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/credentials.json"
            cd "01-gar"
            terraform init
            terraform destroy -auto-approve
            cd ..
